"""Init

Revision ID: 27cbd7110d21
Revises: 
Create Date: 2023-04-28 19:50:15.555063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cbd7110d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('level', sa.Enum('Easy', 'Medium', 'Master', name='qualification'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_id'), 'request', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('picture', sa.String(length=256), nullable=True),
    sa.Column('level', sa.Enum('Easy', 'Medium', 'Master', name='qualification'), nullable=False),
    sa.Column('privilage', sa.Enum('User', 'Moderator', 'Admin', name='privilegelevel'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('workshift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshift_id'), 'workshift', ['id'], unique=False)
    op.create_index(op.f('ix_workshift_start_time'), 'workshift', ['start_time'], unique=False)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshift_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workshift_id'], ['workshift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_id'), 'offer', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workshift_id'], ['workshift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_offer_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_workshift_start_time'), table_name='workshift')
    op.drop_index(op.f('ix_workshift_id'), table_name='workshift')
    op.drop_table('workshift')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_request_id'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
